# https://github.com/hectorqin/reader/blob/master/doc.md
---
services:
  # 书源集合: https://legado.aoaostar.com 点击打开连接 添加远程书源即可
  # 公众号汇总: https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MjM5MzMyMDgyMA==&action=getalbum&album_id=2397535253763801090#wechat_redirect
  reader:
    image: hectorqin/reader:3.2.14
    container_name: reader
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - $PWD/logs:/logs #log映射目录 /home/reader/logs 映射目录可自行修改
      - $PWD/storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50 # 用户上限 默认50
      - READER_APP_USERBOOKLIMIT=200 # 用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true # 开启缓存章节内容 V2.0
      - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 # 开启远程webview
      # 多用户模式配置
      - READER_APP_SECURE=true # 开启登录鉴权 开启后将支持多用户模式
      - READER_APP_SECUREKEY=zVGmsywhNLI8VSG # 管理员密码 建议修改
      - READER_APP_INVITECODE=huBf38sm # 注册邀请码
    networks:
      - reader

  remote-webview:
    image: hectorqin/remote-webview:3.2.0
    container_name: remote-webview
    restart: unless-stopped
    # ports:
    #   - 8050:8050
    networks:
      - reader

networks:
  reader:
    driver: bridge
