---
name: "Build Nginx"

on:
  workflow_dispatch:

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      renew: ${{ steps.vers.outputs.renew }}
      ngx_version: ${{ steps.vers.outputs.ngx_version }}
      acme_version: ${{ steps.vers.outputs.acme_version }}
      zstd_version: ${{ steps.vers.outputs.zstd_version }}
      headers_more_tag: ${{ steps.vers.outputs.headers_more_tag }}

    steps:
      - name: "Get Version and Decide"
        id: vers
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eEuxo pipefail
          RENEW="false"
          LATEST_VER="$(gh release list -R nginx/nginx --limit 1000 | awk '{print $1}' | sed 's#^release-##' | grep -E '^[0-9.]+$' | sort -V | tail -1)"
          LATEST_IMG_VER="$(docker run --rm nginx:${LATEST_VER}-alpine sh -c "nginx -v 2>&1" 2>/dev/null | awk -F'[/ ]' '{print $NF}' || true)"
          CURRENT_VER="$(skopeo list-tags "docker://docker.io/$DOCKERHUB_REPO" 2>/dev/null | jq -r '.Tags[]' | grep -E -- '-alpine$' | sort -rV | head -n1 | sed 's#-alpine$##' || true)"
          ACME_VER="$(gh release view -R nginx/nginx-acme --json tagName -q .tagName | sed 's#v##')"
          ZSTD_VER="$(gh release view -R facebook/zstd --json tagName -q .tagName | sed 's#v##')"
          HEADERS_MORE_TAG="$(gh api repos/openresty/headers-more-nginx-module/tags -q '.[].name' | sort -rV | head -n1 | sed 's#v##')"
          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$LATEST_VER" && "$LATEST_VER" == "$LATEST_IMG_VER" ]] || \
            [[ -z "$CURRENT_VER" && "$LATEST_VER" == "$LATEST_IMG_VER" ]]; then
            echo "Build required."
            RENEW="true"
          fi
          echo "renew=${RENEW}" >> "$GITHUB_OUTPUT"
          echo "ngx_version=${LATEST_VER}" >> "$GITHUB_OUTPUT"
          echo "acme_version=${ACME_VER}" >> "$GITHUB_OUTPUT"
          echo "zstd_version=${ZSTD_VER}" >> "$GITHUB_OUTPUT"
          echo "headers_more_tag=${HEADERS_MORE_TAG}" >> "$GITHUB_OUTPUT"

  notify:
    name: "Send telegram message"
    runs-on: ubuntu-latest
    needs: [check]

    steps:
      - name: ""
        run: |
          BUILD_TIME="$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")"
          echo "BUILD_TIME=$BUILD_TIME" >> "$GITHUB_ENV"

      - name: "Send telegram message"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ env.BUILD_TIME }}

            Upgrade Nginx to version ${{ needs.check.outputs.ngx_version }}
