---
name: "Update dockerfile images"

on:
  push:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ""

jobs:
  update:
    name: "Update dockerfile images"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - name: "Setup updatecli"
        uses: updatecli/updatecli-action@main

      - name: "Update dockerfile images"
        shell: bash
        run: |
          set -eEuo pipefail
          cat > "$RUNNER_TEMP/updatecli.yaml" <<'EOF'
          name: "Update dockerfile images"
          autodiscovery:
            crawlers:
              dockerfile:
                digest: true
          EOF
          updatecli pipeline apply --config "$RUNNER_TEMP/updatecli.yaml"

      - name: "Check for changes"
        shell: bash
        id: diff
        run: |
          set -eEuo pipefail
          git diff --stat
          git diff
          [ -z "$(git status --porcelain)" ] || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: "Commit and push changes"
        if: steps.diff.outputs.changed != ''
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --no-verify --signoff -m "chore(deps): bump images version by github actions [no ci]"
          git push ${{ inputs.ref }}
